/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.test.test;

import id.test.test.Scenes.LoginScene;
import javafx.application.Application;
import javafx.geometry.Rectangle2D;
import javafx.stage.Screen;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        Rectangle2D screenBounds = Screen.getPrimary().getVisualBounds();

        LoginScene loginScene = new LoginScene(primaryStage);
        primaryStage.setScene(loginScene.getScene());

        primaryStage.setWidth(screenBounds.getWidth());
        primaryStage.setHeight(screenBounds.getHeight());
        primaryStage.setMaximized(true);
        primaryStage.show();
    }

}
